Algoritmo "Média de 3 notas"
// Descrição   : Calcula média de 3 notas
// Autor(a)    : Jaime Figueiredo
// Data atual  : 21/09/2017
Var
nota1,nota2,nota3,media:real

Inicio
escreva("Qual é a primeira nota ?")
leia(nota1)
escreva("Qual é asegunda nota ?")
leia(nota2)
escreva("Qual é a terceira nota ?")
leia(nota3)
media<-(nota1+nota2+nota3)/3
escreva("A média é",media)

Fimalgoritmo