Algoritmo "Volume Paralelípípedo"
// Descrição   : Calcula o Volume de um Paralelípípedo
// Autor(a)    : Jaime Figueiredo
// Data atual  : 21/09/2017
Var
comprimento,altura,volume,largura:real

Inicio
escreva("Qual é o comprimento ?")
leia (comprimento)
escreva("Qual é a altura ?")
leia(altura)
escreva("Qual é a largura?")
leia(largura)
volume <-comprimento*largur*altura
escreva("O volume é ",volume)

Fimalgoritmo