Algoritmo "Área do Trapézio"
// Descrição   : Calcula a área do trapézio
// Autor(a)    : Jaime Figueiredo
// Data atual  : 21/09/2017
Var
basemaior,altura,basemenor,area:real

Inicio
escreva ("Qual é a medida da base maior ?")
leia(basemaior)
escreva("Qual é a base menor ?")
leia(basemenor)
escreva("Qual é a altura ?")
leia(altura)
area<-(basemaior+basemenor) * altura/2
escreva("Área é ",area)


Fimalgoritmo